### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ZHANITEST** [DerelictOrg/DerelictFI#10]
```
freeImageTest ~master: building configuration "application"...
source\app.d(2,8): Error: module freeimage is in file 'derelict\freeimage\freeimage.d' which cannot be read
import path[0] = source
import path[1] = C:\D\dmd2\windows\bin\..\..\src\phobos
import path[2] = C:\D\dmd2\windows\bin\..\..\src\druntime\import
dmd failed with exit code 1.
```

That's it. I can't build them.
I used DMD32 D Compiler v2.071.1 and code is here:
```
import std.stdio;
import derelict.freeimage.freeimage;
void main(string[] args)
{
	DerelictFI.load();	`
}
```

```
{
	"name": "miniapp",
	"authors": [
		"dummy"
	],
	"description": "A minimal D application.",
	"copyright": "Copyright © 2016, dummy",
	"license": "proprietary",
	"derelict-fi": "~>2.0.2"
}
```

**Comment by mdparker** [comment]
The error you're seeing is usually because you've either imported a module that doest exist or you haven't properly configured your import path. You've got the module name correct, so that means you should look at the import path.

Since you are using DUB, and since DUB handles configuration of the import path for you, then the first place to check is your configuration file. Sure enough, you have a problem with it. You haven't properly specified your dependency on DerelictFI. A visit to [the package format documentation](https://code.dlang.org/package-format?lang=json) (the JSON version, since that's the syntax you're using) will show you how to properly specify dependencies:

```
"dependencies": {
    "derelict-fi": "~>2.0.2"
}
```
In future, please take any such problems to the [D Learn forum](http://forum.dlang.org/group/learn). This issue tracker should only be used to report actual issues with the library, not as a support forum.
